### ISSUE TITLE
Add ability to override shell used

### ISSUE THREAD

**Issue by jamietanna** [saschagrunert/demo#117]
I.e. if I were to try and run `demo` with an Alpine-based distro, I receive the error:

```
2023/09/23 13:51:56 run failed: step command failed: exec: "bash": executable file not found in $PATH
exit status 1
```

**Comment by saschagrunert** [comment]
Sounds like a good feature, are you interested in contributing it @jamietanna? :slightly_smiling_face:

**Comment by jamietanna** [comment]
I'd be happy to! Any preference on the CLI option name that we'd be adding for this?

**Comment by saschagrunert** [comment]
@jamietanna I'm open to suggestions, thank you!

**Comment by saschagrunert** [comment]
> Maybe `--shell` (with no short option)?

Sounds good to me.
